#!/bin/sh
DIR=$(dirname $0)
cd $DIR
if [ -e run.pid ]; then
    echo "A file named $DIR/run.pid already exists. Please run ./stop or remove the file."
    exit
fi
./mvnw spring-boot:run >& run.log &
RUN_PID=$!
echo $RUN_PID > run.pid
START_MSG="Started RestServiceApplication"
echo "Process starting as PID $RUN_PID. Logging to $DIR/run.log."
echo "Using default host: localhost and port: 8080."
( tail -f -n0 run.log & ) | grep -q "$START_MSG"
echo $START_MSG
